/*
 * datumboxmachinelearningapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/23/2016
 */

package models_pkg


/*
 * Structure for the custom type BaseResponse
 */
type BaseResponse struct {
    Status          int64           `json:"status" form:"status"` //If an error occurs while executing your call, our API will return a status of 0 else 1.
    Error           Error           `json:"error" form:"error"` //contains description of error. its an object which contains member error no and error description
}

/*
 * Structure for the custom type Error
 */
type Error struct {
    ErrorCode       int64           `json:"ErrorCode" form:"ErrorCode"` //contains error code no
    ErrorMessage    string          `json:"ErrorMessage" form:"ErrorMessage"` //Contains description of error
}

/*
 * Structure for the custom type InheritedForResult
 */
type InheritedForResult struct {
    BaseResponse    // Anonymous member to emulate model inheritence
    Result          string          `json:"result" form:"result"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type InheritedOutput
 */
type InheritedOutput struct {
    Output          InheritedForResult `json:"output" form:"output"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type InheritedDocumentSimilarityResponse
 */
type InheritedDocumentSimilarityResponse struct {
    BaseResponse    // Anonymous member to emulate model inheritence
    Result          DocumentSimilarityResponse `json:"result" form:"result"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type DocumentSimilarityResponse
 */
type DocumentSimilarityResponse struct {
    Oliver          float64         `json:"Oliver" form:"Oliver"` //TODO: Write general description for this field
    Shingle         float64         `json:"Shingle" form:"Shingle"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type ObjectForDocument
 */
type ObjectForDocument struct {
    Output          InheritedDocumentSimilarityResponse `json:"output" form:"output"` //TODO: Write general description for this field
}
