/*
 * datumboxmachinelearningapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/23/2016
 */
package documentclassification_pkg


import(
	"encoding/json"
	"datumboxmachinelearningapi_lib/models_pkg"
	"github.com/apimatic/unirest-go"
	"datumboxmachinelearningapi_lib"
	"datumboxmachinelearningapi_lib/apihelper_pkg"
)
/*
 * Client structure as interface implementation
 */
type DOCUMENTCLASSIFICATION_IMPL struct { }

/**
 * The Sentiment Analysis function classifies documents as positive, negative or neutral (lack of sentiment) depending on whether they express a positive, negative or neutral opinion.
 * @param    string        apiKey      parameter: Required
 * @param    string        text        parameter: Required
 * @return	Returns the *models_pkg.InheritedOutput response from the API call
 */
func (me *DOCUMENTCLASSIFICATION_IMPL) CreateSentimentAnalysis (
            apiKey string,
            text string) (*models_pkg.InheritedOutput, error) {
        //the base uri for api requests
    _queryBuilder := datumboxmachinelearningapi_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/1.0/SentimentAnalysis.json"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
    }

    //form parameters
    parameters := map[string]interface{} {

        "api_key" : apiKey,
        "text" : text,

    }


    //prepare API request
    _request := unirest.Post(_queryBuilder, headers, parameters)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal *models_pkg.InheritedOutput = &models_pkg.InheritedOutput{}
    err = json.Unmarshal(_response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

/**
 * The Twitter Sentiment Analysis function allows you to perform Sentiment Analysis on Twitter. It classifies the tweets as positive, negative or neutral depending on their context.
 * @param    string        apiKey      parameter: Required
 * @param    string        text        parameter: Required
 * @return	Returns the *models_pkg.InheritedOutput response from the API call
 */
func (me *DOCUMENTCLASSIFICATION_IMPL) CreateTwitterSentimentAnalysis (
            apiKey string,
            text string) (*models_pkg.InheritedOutput, error) {
        //the base uri for api requests
    _queryBuilder := datumboxmachinelearningapi_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/1.0/TwitterSentimentAnalysis.json "

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
    }

    //form parameters
    parameters := map[string]interface{} {

        "api_key" : apiKey,
        "text" : text,

    }


    //prepare API request
    _request := unirest.Post(_queryBuilder, headers, parameters)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal *models_pkg.InheritedOutput = &models_pkg.InheritedOutput{}
    err = json.Unmarshal(_response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

/**
 * The Subjectivity Analysis function categorizes documents as subjective or objective based on their writing style. Texts that express personal opinions are labeled as subjective and the others as objective.
 * @param    string        apiKey      parameter: Required
 * @param    string        text        parameter: Required
 * @return	Returns the *models_pkg.InheritedOutput response from the API call
 */
func (me *DOCUMENTCLASSIFICATION_IMPL) CreateSubjectivityAnalysis (
            apiKey string,
            text string) (*models_pkg.InheritedOutput, error) {
        //the base uri for api requests
    _queryBuilder := datumboxmachinelearningapi_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/1.0/SubjectivityAnalysis.json "

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
    }

    //form parameters
    parameters := map[string]interface{} {

        "api_key" : apiKey,
        "text" : text,

    }


    //prepare API request
    _request := unirest.Post(_queryBuilder, headers, parameters)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal *models_pkg.InheritedOutput = &models_pkg.InheritedOutput{}
    err = json.Unmarshal(_response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

/**
 * The Topic Classification function assigns documents in 12 thematic categories based on their keywords, idioms and jargon. It can be used to identify the topic of the texts.
 * @param    string        apiKey      parameter: Required
 * @param    string        text        parameter: Required
 * @return	Returns the *models_pkg.InheritedOutput response from the API call
 */
func (me *DOCUMENTCLASSIFICATION_IMPL) CreateTopicClassification (
            apiKey string,
            text string) (*models_pkg.InheritedOutput, error) {
        //the base uri for api requests
    _queryBuilder := datumboxmachinelearningapi_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/1.0/TopicClassification.json "

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
    }

    //form parameters
    parameters := map[string]interface{} {

        "api_key" : apiKey,
        "text" : text,

    }


    //prepare API request
    _request := unirest.Post(_queryBuilder, headers, parameters)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal *models_pkg.InheritedOutput = &models_pkg.InheritedOutput{}
    err = json.Unmarshal(_response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

/**
 * The Spam Detection function labels documents as spam or nospam by taking into account their context. It can be used to filter out spam emails and comments.
 * @param    string        apiKey      parameter: Required
 * @param    string        text        parameter: Required
 * @return	Returns the *models_pkg.InheritedOutput response from the API call
 */
func (me *DOCUMENTCLASSIFICATION_IMPL) CreateSpamDetection (
            apiKey string,
            text string) (*models_pkg.InheritedOutput, error) {
        //the base uri for api requests
    _queryBuilder := datumboxmachinelearningapi_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/1.0/SpamDetection.json "

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
    }

    //form parameters
    parameters := map[string]interface{} {

        "api_key" : apiKey,
        "text" : text,

    }


    //prepare API request
    _request := unirest.Post(_queryBuilder, headers, parameters)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal *models_pkg.InheritedOutput = &models_pkg.InheritedOutput{}
    err = json.Unmarshal(_response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

/**
 * The Adult Content Detection function classifies the documents as adult or noadult based on their context. It can be used to detect whether a document contains content unsuitable for minors.
 * @param    string        apiKey      parameter: Required
 * @param    string        text        parameter: Required
 * @return	Returns the *models_pkg.InheritedOutput response from the API call
 */
func (me *DOCUMENTCLASSIFICATION_IMPL) CreateAdultContentDetection (
            apiKey string,
            text string) (*models_pkg.InheritedOutput, error) {
        //the base uri for api requests
    _queryBuilder := datumboxmachinelearningapi_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/1.0/AdultContentDetection.json "

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
    }

    //form parameters
    parameters := map[string]interface{} {

        "api_key" : apiKey,
        "text" : text,

    }


    //prepare API request
    _request := unirest.Post(_queryBuilder, headers, parameters)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal *models_pkg.InheritedOutput = &models_pkg.InheritedOutput{}
    err = json.Unmarshal(_response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

/**
 * The Readability Assessment function determines the degree of readability of a document based on its terms and idioms. The texts are classified as basic, intermediate and advanced depending their difficulty.
 * @param    string        apiKey      parameter: Required
 * @param    string        text        parameter: Required
 * @return	Returns the *models_pkg.InheritedOutput response from the API call
 */
func (me *DOCUMENTCLASSIFICATION_IMPL) CreateReadabilityAssessment (
            apiKey string,
            text string) (*models_pkg.InheritedOutput, error) {
        //the base uri for api requests
    _queryBuilder := datumboxmachinelearningapi_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/1.0/ReadabilityAssessment.json "

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
    }

    //form parameters
    parameters := map[string]interface{} {

        "api_key" : apiKey,
        "text" : text,

    }


    //prepare API request
    _request := unirest.Post(_queryBuilder, headers, parameters)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal *models_pkg.InheritedOutput = &models_pkg.InheritedOutput{}
    err = json.Unmarshal(_response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

/**
 * The Language Detection function identifies the natural language of the given document based on its words and context. This classifier is able to detect 96 different languages.
 * @param    string        apiKey      parameter: Required
 * @param    string        text        parameter: Required
 * @return	Returns the *models_pkg.InheritedOutput response from the API call
 */
func (me *DOCUMENTCLASSIFICATION_IMPL) CreateLanguageDetection (
            apiKey string,
            text string) (*models_pkg.InheritedOutput, error) {
        //the base uri for api requests
    _queryBuilder := datumboxmachinelearningapi_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/1.0/LanguageDetection.json "

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
    }

    //form parameters
    parameters := map[string]interface{} {

        "api_key" : apiKey,
        "text" : text,

    }


    //prepare API request
    _request := unirest.Post(_queryBuilder, headers, parameters)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal *models_pkg.InheritedOutput = &models_pkg.InheritedOutput{}
    err = json.Unmarshal(_response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

/**
 * The Commercial Detection function labels the documents as commercial or non-commercial based on their keywords and expressions. It can be used to detect whether a website is commercial or not.
 * @param    string        apiKey      parameter: Required
 * @param    string        text        parameter: Required
 * @return	Returns the *models_pkg.InheritedOutput response from the API call
 */
func (me *DOCUMENTCLASSIFICATION_IMPL) CreateCommercialDetection (
            apiKey string,
            text string) (*models_pkg.InheritedOutput, error) {
        //the base uri for api requests
    _queryBuilder := datumboxmachinelearningapi_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/1.0/CommercialDetection.json "

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
    }

    //form parameters
    parameters := map[string]interface{} {

        "api_key" : apiKey,
        "text" : text,

    }


    //prepare API request
    _request := unirest.Post(_queryBuilder, headers, parameters)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal *models_pkg.InheritedOutput = &models_pkg.InheritedOutput{}
    err = json.Unmarshal(_response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

/**
 * The Educational Detection function classifies the documents as educational or non-educational based on their context. It can be used to detect whether a website is educational or not.
 * @param    string        apiKey      parameter: Required
 * @param    string        text        parameter: Required
 * @return	Returns the *models_pkg.InheritedOutput response from the API call
 */
func (me *DOCUMENTCLASSIFICATION_IMPL) CreateEducationalDetection (
            apiKey string,
            text string) (*models_pkg.InheritedOutput, error) {
        //the base uri for api requests
    _queryBuilder := datumboxmachinelearningapi_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/1.0/EducationalDetection.json "

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
    }

    //form parameters
    parameters := map[string]interface{} {

        "api_key" : apiKey,
        "text" : text,

    }


    //prepare API request
    _request := unirest.Post(_queryBuilder, headers, parameters)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal *models_pkg.InheritedOutput = &models_pkg.InheritedOutput{}
    err = json.Unmarshal(_response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

/**
 * The Gender Detection function identifies if a particular document is written-by or targets-to a man or a woman based on the context, the words and the idioms found in the text.
 * @param    string        apiKey      parameter: Required
 * @param    string        text        parameter: Required
 * @return	Returns the *models_pkg.InheritedOutput response from the API call
 */
func (me *DOCUMENTCLASSIFICATION_IMPL) CreateGenderDetection (
            apiKey string,
            text string) (*models_pkg.InheritedOutput, error) {
        //the base uri for api requests
    _queryBuilder := datumboxmachinelearningapi_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/1.0/GenderDetection.json "

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
    }

    //form parameters
    parameters := map[string]interface{} {

        "api_key" : apiKey,
        "text" : text,

    }


    //prepare API request
    _request := unirest.Post(_queryBuilder, headers, parameters)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal *models_pkg.InheritedOutput = &models_pkg.InheritedOutput{}
    err = json.Unmarshal(_response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

