/*
 * datumboxmachinelearningapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/23/2016
 */

package documentclassification_pkg

import "datumboxmachinelearningapi_lib/models_pkg"

/*
 * Interface for the DOCUMENTCLASSIFICATION_IMPL
 */
type DOCUMENTCLASSIFICATION interface {
    CreateSentimentAnalysis (string, string) (*models_pkg.InheritedOutput, error)

    CreateTwitterSentimentAnalysis (string, string) (*models_pkg.InheritedOutput, error)

    CreateSubjectivityAnalysis (string, string) (*models_pkg.InheritedOutput, error)

    CreateTopicClassification (string, string) (*models_pkg.InheritedOutput, error)

    CreateSpamDetection (string, string) (*models_pkg.InheritedOutput, error)

    CreateAdultContentDetection (string, string) (*models_pkg.InheritedOutput, error)

    CreateReadabilityAssessment (string, string) (*models_pkg.InheritedOutput, error)

    CreateLanguageDetection (string, string) (*models_pkg.InheritedOutput, error)

    CreateCommercialDetection (string, string) (*models_pkg.InheritedOutput, error)

    CreateEducationalDetection (string, string) (*models_pkg.InheritedOutput, error)

    CreateGenderDetection (string, string) (*models_pkg.InheritedOutput, error)
}

/*
 * Factory for the DOCUMENTCLASSIFICATION interaface returning DOCUMENTCLASSIFICATION_IMPL
 */
func NewDOCUMENTCLASSIFICATION() DOCUMENTCLASSIFICATION {
    return &DOCUMENTCLASSIFICATION_IMPL{}
}