/*
 * datumboxmachinelearningapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/23/2016
 */
package informationretrieval_pkg


import(
	"encoding/json"
	"datumboxmachinelearningapi_lib/models_pkg"
	"github.com/apimatic/unirest-go"
	"datumboxmachinelearningapi_lib"
	"datumboxmachinelearningapi_lib/apihelper_pkg"
)
/*
 * Client structure as interface implementation
 */
type INFORMATIONRETRIEVAL_IMPL struct { }

/**
 * The Text Extraction function enables you to extract the important information from a given webpage. Extracting the clear text of the documents is an important step before any other analysis
 * @param    string        apiKey      parameter: Required
 * @param    string        text        parameter: Required
 * @return	Returns the *models_pkg.InheritedOutput response from the API call
 */
func (me *INFORMATIONRETRIEVAL_IMPL) CreateTextExtraction (
            apiKey string,
            text string) (*models_pkg.InheritedOutput, error) {
        //the base uri for api requests
    _queryBuilder := datumboxmachinelearningapi_lib.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + "/1.0/TextExtraction.json "

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
    }

    //form parameters
    parameters := map[string]interface{} {

        "api_key" : apiKey,
        "text" : text,

    }


    //prepare API request
    _request := unirest.Post(_queryBuilder, headers, parameters)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
        err = apihelper_pkg.NewAPIError("HTTP Response Not OK" , _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal *models_pkg.InheritedOutput = &models_pkg.InheritedOutput{}
    err = json.Unmarshal(_response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

