/*
 * datumboxmachinelearningapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/23/2016
 */

package informationretrieval_pkg

import "datumboxmachinelearningapi_lib/models_pkg"

/*
 * Interface for the INFORMATIONRETRIEVAL_IMPL
 */
type INFORMATIONRETRIEVAL interface {
    CreateTextExtraction (string, string) (*models_pkg.InheritedOutput, error)
}

/*
 * Factory for the INFORMATIONRETRIEVAL interaface returning INFORMATIONRETRIEVAL_IMPL
 */
func NewINFORMATIONRETRIEVAL() INFORMATIONRETRIEVAL {
    return &INFORMATIONRETRIEVAL_IMPL{}
}