/*
 * datumboxmachinelearningapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/23/2016
 */

package datumboxmachinelearningapi_lib

/** The base Uri for API calls */
const BASEURI string = "http://api.datumbox.com"

